#!/usr/bin/env zsh

##
## Global config
##
DIRNAME_CLI=/usr/bin/dirname
PWD_CLI=/bin/pwd
UNAME_CLI=/usr/bin/uname
SYSTEM_PLATFORM=$($UNAME_CLI)

echo "[$SYSTEM_PLATFORM] Applying preset options ..."
MY_PROJECT_LIBSSH2_WITH_DISABLED_TEST_APPS=ON
MY_PROJECT_LIBSSH2_WITH_ZLIB=ON
MY_PROJECT_NETSNMP_WITH_DISABLED_APPS=OFF
MY_PROJECT_NETSNMP_WITH_DISABLED_MIB_LOADING=OFF
MY_PROJECT_NETSNMP_WITH_IPV6=ON
MY_PROJECT_NETSNMP_WITH_LIBSSH2=ON
MY_PROJECT_NETSNMP_WITH_SSL=ON
MY_PROJECT_OPENSSL_WITH_DEPRECATED_CIPHERS=ON
MY_PROJECT_OPENSSL_WITH_DISABLED_APPS=ON
MY_PROJECT_OPENSSL_WITH_ZLIB=ON
MY_PROJECT_ZLIB_WITH_DISABLED_TEST_APPS=ON
echo "[$SYSTEM_PLATFORM] Applying default options ... DONE"

SCRIPT_DIR=$(cd -- "$(${DIRNAME_CLI} "${BASH_SOURCE[0]:-${(%):-%x}}")" &> /dev/null && ${PWD_CLI})
source $SCRIPT_DIR/build-darwin.zsh
