@echo off

setlocal
echo [Windows] Applying preset options ...
set MY_PROJECT_LIBSSH2_WITH_ZLIB=ON
set MY_PROJECT_LIBSSH2_WITHOUT_TEST_APPS=ON
set MY_PROJECT_NETSNMP_WITH_IPV6=ON
set MY_PROJECT_NETSNMP_WITH_LIBSSH2=ON
set MY_PROJECT_NETSNMP_WITH_SSL=ON
set MY_PROJECT_NETSNMP_WITH_WINEXTDLL=ON
set MY_PROJECT_NETSNMP_WITHOUT_APPS=OFF
set MY_PROJECT_NETSNMP_WITHOUT_MIB_LOADING=OFF
set MY_PROJECT_OPENSSL_WITH_DEPRECATED_CIPHERS=ON
set MY_PROJECT_OPENSSL_WITH_ZLIB=ON
set MY_PROJECT_OPENSSL_WITHOUT_APPS=ON
set MY_PROJECT_ZLIB_WITHOUT_TEST_APPS=ON
echo [Windows] Applying default options ... DONE
call %~dp0\build-windows.cmd
endlocal
